Controllers/WebSiteTempleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementViewSite.Controllers
{
    public class WebSiteTempleteController : Controller
    {
        // GET: WebSiteTemplete
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Category()
        {
            return View("Category");
        }
        public ActionResult About()
        {
            return View("About");
        }

    }
}

Views/_WebSiteLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @RenderSection("head", false)
    
</head>
<body>

    <div class="container">
        <div>
            <h1>This is Header</h1>
            <hr />
            @Html.ActionLink("Home", "Index", "WebSiteTemplete")
            @Html.ActionLink("About", "About", "WebSiteTemplete")
            @Html.ActionLink("Category", "Category", "WebSiteTemplete")
        </div>

        <div style="background-color:mediumturquoise">
            @RenderBody()
        </div>

        <div>
            This is Footer
        </div>

    </div>


</body>
</html>